name: CI/CD Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t legacy-backend .

      - name: Extract app folder from Docker container
        run: |
          id=$(docker create legacy-backend)
          docker cp $id:/app ./build
          docker rm -v $id

      - name: Verify build contents
        run: |
          ls -la ./build | head -n 20
          ls -la ./build/node_modules | head -n 20

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: /express-backend.api.tqpartner.my.id/backend-legacy/

